start ::= assignment
        | expression
        | program

assignment ::= NAME index? ':' expression

expression ::= value index? arithmetic?

value ::= '(' expression ')'
        | STRING
        | NAME
        | SIGNED_INTEGER
        | LIST
        | unaryFunction

arithmetic ::= '+' expression
             | '-' expression
             | 'x' expression
             | '%' expression
             | '|' expression
             | concatenation

concatenation ::= ',' expression
                | comparison

comparison ::= '=' expression
             | 'n' expression
             | '<' expression
             | 'l' expression
             | '>' expression
             | 'g' expression
             | minimax

minimax ::= 'r' expression
          | '_' expression

index ::= '[' expression ']'

unaryFunction ::= 'i' expression
                | 'p' expression
                | "+/" expression

program ::= programDefinition
          | programCall
          | programEdit

programDefinition ::= 'v' NAME '\n' .* 'v'
                    | 'v' NAME ':' NAME NAME

programDefinition ::= 'v' NAME ( ':' NAME NAME )? '\n'
                      ( .* '\n' )*
                      'v'

programCall ::= NAME

programEdit ::= 'v' NAME '[' editCommand ']' .* 'v'

editCommand ::= 'u' INTEGER
              | 'b'
              | INTEGER

STRING ::= '\'' .* '\''

SIGNED_INTEGER ::= '~'? INTEGER

INTEGER ::= DIGIT+

DIGIT* ::= '0' .. '9'

NAME ::= UPPERCASE+

UPPERCASE* ::= 'A' .. 'Z'
